server:
  port: 8085

topic: "fast-data-topic"

spring:
  kafka:
    consumer:
      enable-auto-commit: true
      group-id: "kconsumer-grp"
      client-id: "kconsumer-app"
      bootstrap-servers: my-cluster-kafka-bootstrap:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        auto.commit.interval.ms: 5000
        max.poll.interval.ms: 300000
        max.poll.records: 300
        session.timeout.ms: 30000
        heartbeat.interval.ms: 1000
        partition.assignment.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - info