apiVersion: thenextapps.com/v1alpha1
kind: KconsumerGroup
metadata:
  name: kconsumer
spec:
  minReplicas: 1
  averageRecordsLagLimit: 1000
  consumerSpec:
    containerName: kconsumer
    image: thenextapps/kconsumer:latest
    topic: fast-data-topic
