// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumerSpec) DeepCopyInto(out *ConsumerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumerSpec.
func (in *ConsumerSpec) DeepCopy() *ConsumerSpec {
	if in == nil {
		return nil
	}
	out := new(ConsumerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KconsumerGroup) DeepCopyInto(out *KconsumerGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KconsumerGroup.
func (in *KconsumerGroup) DeepCopy() *KconsumerGroup {
	if in == nil {
		return nil
	}
	out := new(KconsumerGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KconsumerGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KconsumerGroupList) DeepCopyInto(out *KconsumerGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KconsumerGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KconsumerGroupList.
func (in *KconsumerGroupList) DeepCopy() *KconsumerGroupList {
	if in == nil {
		return nil
	}
	out := new(KconsumerGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KconsumerGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KconsumerGroupSpec) DeepCopyInto(out *KconsumerGroupSpec) {
	*out = *in
	out.ConsumerSpec = in.ConsumerSpec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KconsumerGroupSpec.
func (in *KconsumerGroupSpec) DeepCopy() *KconsumerGroupSpec {
	if in == nil {
		return nil
	}
	out := new(KconsumerGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KconsumerGroupStatus) DeepCopyInto(out *KconsumerGroupStatus) {
	*out = *in
	if in.ActivePods != nil {
		in, out := &in.ActivePods, &out.ActivePods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KconsumerGroupStatus.
func (in *KconsumerGroupStatus) DeepCopy() *KconsumerGroupStatus {
	if in == nil {
		return nil
	}
	out := new(KconsumerGroupStatus)
	in.DeepCopyInto(out)
	return out
}
