apiVersion: apps/v1
kind: Deployment
metadata:
  name: kconsumer-group-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kconsumer-group-operator
  template:
    metadata:
      labels:
        name: kconsumer-group-operator
    spec:
      serviceAccountName: kconsumer-group-operator
      containers:
        - name: kconsumer-group-operator
          # Replace this with the built image name
          image: thenextapps/kconsumer-group-operator:v0.0.1
          command:
          - kconsumer-group-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kconsumer-group-operator"
