apiVersion: apps/v1
kind: Deployment
metadata:
  name: kproducer
  labels:
    app: kproducer
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kproducer
  template:
    metadata:
      labels:
        app: kproducer
    spec:
      containers:
      - name: kproducer
        image: thenextapps/kproducer:latest
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: kproducer-service
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app: kproducer
